name: club_user
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ########
  # Core #
  ########
  club_model:
    git:
      url: https://github.com/patelmeet341993/club_model
      ref: dishant

  #######
  # UI #
  #######
  circular_countdown_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/extra/
    - assets/lotties/